# Generated by Django 5.2.1 on 2025-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField()),
                ('cidade', models.CharField()),
                ('zip_code', models.CharField()),
                ('telefone_wpp', models.CharField()),
                ('instagram_or_website', models.CharField()),
                ('descricao', models.TextField()),
                ('como_conheceu', models.TextField(null=True)),
            ],
        ),
    ]
