# Generated by Django 5.2.1 on 2025-05-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaEmCasaApp', '0002_negocio_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='senha',
        ),
    ]
