# Generated by Django 5.2.1 on 2025-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaEmCasaApp', '0003_remove_negocio_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='negocio',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='longitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='numero',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='rua',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
