# Generated by Django 5.2.1 on 2025-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaEmCasaApp', '0004_remove_negocio_zip_code_negocio_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
