# Generated by Django 5.2.1 on 2025-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaEmCasaApp', '0005_alter_negocio_latitude_alter_negocio_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='estado',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
