# Generated by Django 5.2.1 on 2025-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaEmCasaApp', '0006_negocio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='permitido',
            field=models.BooleanField(default=False),
        ),
    ]
